dist: trusty
language: go
go: '1.10'

install:
  - make setup
  - gem install fpm

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

script:
  - make ci

notifications:
  email: false
