baseURL = "https://install.goreleaser.com/"
languageCode = "en-us"
title = "Install | GoReleaser"
copyright = "Made with ❤️ by GoReleaser contributors."
googleAnalytics = "UA-106198408-2"
theme = "hugo-apex-theme"
pygmentsCodeFences = true
pygmentsStyle = "dracula"